version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    networks:
      - db-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: demo_password
      POSTGRES_USER: demo_user
      POSTGRES_DB: demo_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U demo_user -d demo_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  db-network:
    driver: bridge

volumes:
  postgres_data: